### ISSUE TITLE
getItem error

### ISSUE THREAD

**Issue by Andyauk** [zelbeus/ricx_grave_robbery#1]
```
[script:ricx_grave_ro] SCRIPT ERROR: @ricx_grave_robbery/server.lua:31: attempt to call a nil value (field 'getItem')
[script:ricx_grave_ro] > handler (@ricx_grave_robbery/server.lua:31)
```

not sure why im getting this error.

**Comment by Andyauk** [comment]
> ```
> [script:ricx_grave_ro] SCRIPT ERROR: @ricx_grave_robbery/server.lua:31: attempt to call a nil value (field 'getItem')
> [script:ricx_grave_ro] > handler (@ricx_grave_robbery/server.lua:31)
> ```
> 
> not sure why im getting this error.

ahh I think it might be due to I'm testing out qbr was looking forward to using this. :(

**Comment by zelbeus** [comment]
> > ```
> > [script:ricx_grave_ro] SCRIPT ERROR: @ricx_grave_robbery/server.lua:31: attempt to call a nil value (field 'getItem')
> > [script:ricx_grave_ro] > handler (@ricx_grave_robbery/server.lua:31)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > not sure why im getting this error.
> 
> ahh I think it might be due to I'm testing out qbr was looking forward to using this. :(

Now its compatible with qbr
